(function(){
  'use strict';
  if(window.AvatarUI)return;
  const script=document.currentScript,base=new URL('.',script.src),C=window.AvatarCore;
  if(!C)return;
  const cfg=window.AVATAR_CONFIG||{},surface=cfg.surface||document.body.dataset.page||'compass';
  let profile=C.empty(),master=null,online=false,busy=false,guideData=[],selected='madeleine',active='abend',restoreFocus=null;
  const names={john:'John',madeleine:'Madlene'},icons={john:'◈',madeleine:'✺'};
  const endpoint=()=>{if(cfg.endpoint)return cfg.endpoint;if(typeof JOHN_API!=='undefined')return JOHN_API+'/api/avatare';if(window.INST?.api)return window.INST.api.replace(/\/$/,'')+'/api/avatare';return null;};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const host=document.createElement('div');host.id='avatar-presence';const shadow=host.attachShadow({mode:'open'});
  shadow.innerHTML=`<style>
  :host{font:15px/1.5 system-ui,sans-serif;color:#edf2f7;display:block;margin:12px 0}*{box-sizing:border-box}button,input,textarea,select{font:inherit}button,a{touch-action:manipulation}button{cursor:pointer;border:1px solid #52647b;border-radius:18px;background:#172337;color:#f2f5fa;padding:9px 13px}button:hover,button[aria-pressed=true]{border-color:#d9b560;background:#2d3541}button:disabled{opacity:.55;cursor:default}button:focus-visible,a:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible{outline:3px solid #f1cd78;outline-offset:3px}.strip{display:flex;flex-wrap:wrap;gap:8px;align-items:center;padding:8px 12px;background:#111b29;border:1px solid #394b62;border-radius:16px}.strip small{color:#c4cfdd}.fab{position:fixed;left:14px;bottom:18px;z-index:850;box-shadow:0 6px 28px #0008}dialog{background:#101a28;color:#edf2f7;border:1px solid #53627a;border-radius:20px;width:min(760px,calc(100vw - 24px));max-height:88vh;padding:22px;overflow:auto}dialog::backdrop{background:#030914bb}h2{margin:0;font-size:26px}h3{font-size:19px;margin:18px 0 8px}p{margin:8px 0 14px}small,.muted{color:#b8c6d8}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.top{justify-content:space-between;position:sticky;top:-22px;background:#101a28;z-index:2;padding:8px 0}.tabs{position:sticky;top:34px;background:#101a28;z-index:2;padding:8px 0}.tabs{margin:16px 0}.card{padding:15px;margin:12px 0;border:1px solid #3c4c61;border-radius:14px;background:#162234}label{display:block;margin:12px 0}input,textarea,select{display:block;width:100%;background:#0d1725;color:#edf2f7;border:1px solid #63718a;padding:10px;border-radius:9px}input[type=checkbox]{display:inline;width:auto}a{color:#eacc87}.status{min-height:24px;color:#eacc87}.choices{display:flex;gap:8px;flex-wrap:wrap}.quote{border-left:3px solid #d1b475;padding-left:12px}.guide{padding:14px 0;border-bottom:1px solid #3c4c61}.badge{font-size:12px;border:1px solid #68768a;border-radius:5px;padding:2px 5px}.danger{color:#ffd0cd}@media(max-width:450px){dialog{padding:15px}.strip small{flex-basis:100%}.fab{bottom:12px}}
  </style><div class="strip" aria-label="Deine Begleiter"><button data-avatar="john">◈ John</button><button data-avatar="madeleine">✺ Madlene</button><small>${esc(surface)} · gemeinsam denken, konkret handeln</small></div><button class="fab" aria-haspopup="dialog">◈ John · ✺ Madlene</button><dialog aria-labelledby="av-title"><div class="row top"><h2 id="av-title">Deine Begleiter</h2><button id="close" aria-label="Schließen">✕</button></div><nav class="row tabs" aria-label="Bereiche"><button data-tab="abend">Dein Abend</button><button data-tab="kompass">Mein Kompass</button><button data-tab="wegweiser">30 Wegweiser</button><button data-tab="persoenlichkeit">Persönlichkeiten</button></nav><p class="status" role="status" aria-live="polite"></p><section id="body"></section></dialog>`;
  const anchor=document.querySelector('[data-avatar-slot]')||document.querySelector('main')||document.body;
  anchor.prepend(host);
  const dialog=shadow.querySelector('dialog'),body=shadow.querySelector('#body'),status=shadow.querySelector('.status');
  host.addEventListener('keydown',e=>{if(dialog.open)e.stopPropagation();});
  function note(t){status.textContent=t;}
  async function request(data){const url=endpoint();if(!url)throw Error('Die persönliche Wolkenverbindung ist hier noch nicht eingerichtet.');let ticket='';
  if(!cfg.endpoint && location.protocol==='https:'){const tr=await fetch('/gate.php?wer=1',{credentials:'same-origin',cache:'no-store'});if(tr.ok){const td=await tr.json();ticket=td.madeleine||'';}}
  const r=await fetch(url,{method:data?'POST':'GET',credentials:cfg.credentials||'same-origin',headers:{...(data?{'Content-Type':'application/json'}:{}),...(ticket?{'X-Mad-Ticket':ticket}:{})},body:data?JSON.stringify({...data,revision:profile.revision}):undefined,signal:AbortSignal.timeout(data?.op==='chat'?240000:12000)});const d=await r.json();if(!r.ok||!d.ok)throw Error(r.status===409?'Inzwischen auf einem anderen Gerät geändert. Bitte neu laden; deine Eingaben wurden nicht überschrieben.':r.status===429?'Dein tägliches Gesprächsbudget ist erreicht. Kompass und Abendcheck funktionieren weiter.':r.status===403?'Dieses persönliche Profil ist nur für die Besitzerin oder den Besitzer zugänglich.':r.status===401?'Bitte zuerst anmelden.':r.status===503?'Die persönliche Wolkenverbindung ist noch nicht eingerichtet oder nicht erreichbar.':'Speichern fehlgeschlagen. Bitte erneut versuchen.');profile=d.profile;master=d.master;online=true;return d;}
  async function mutate(data){if(busy)return false;busy=true;shadow.querySelectorAll('[data-write]').forEach(b=>b.disabled=true);try{await request(data);note('In deinem persönlichen Wolkenprofil gespeichert.');window.dispatchEvent(new CustomEvent('avatar-profile-changed',{detail:profile}));return true;}catch(e){note(e.message);return false;}finally{busy=false;shadow.querySelectorAll('[data-write]').forEach(b=>b.disabled=!online);}}
  async function open(tab,avatar){active=tab||active;if(avatar&&avatar!==selected)conversation=[];selected=avatar||selected;restoreFocus=document.activeElement;if(!dialog.open)dialog.showModal();note('Persönliches Profil wird geladen …');try{await request();note('Wolke verbunden · persönliche Anpassungen getrennt vom Master');}catch(e){online=false;profile=C.empty();master=null;note(e.message+' Vorschau ohne Speicherung.');}render();}
  function close(){dialog.close();restoreFocus?.focus();}
  function render(){shadow.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===active)));if(active==='abend')evening();if(active==='kompass')compass();if(active==='wegweiser')guides();if(active==='persoenlichkeit')personalities();shadow.querySelectorAll('[data-write]').forEach(b=>b.disabled=!online);}
  function evening(){const opts=C.ranked(profile);const pending=(profile.events||[]).filter(e=>e.status==='geplant').slice(-3);body.innerHTML=`<h3>Was brauchst du heute Abend?</h3><p>Verbindung, Energie, Ruhe oder Zeit für dich. Häufig genutzte und hilfreiche Möglichkeiten rücken nach oben.</p><div class="choices">${opts.map(o=>`<button data-choice="${esc(o.id)}">${esc(o.label)}</button>`).join('')}</div><div id="response" aria-live="polite"></div>${pending.length?'<h3>Deine offenen Vorhaben</h3>':''}${pending.map(e=>`<div class="card"><b>${esc(e.label)}</b><p>${esc(e.next)}</p><label>Wie war die Wirkung?<select data-effect="${esc(e.eventId)}"><option value="offen">Noch offen</option><option value="gut">Hat gutgetan</option><option value="neutral">Neutral</option><option value="anstrengend">War anstrengend</option></select></label><div class="row"><button data-write data-done="${esc(e.eventId)}">Habe ich gemacht</button><button data-write data-skip="${esc(e.eventId)}">Heute ausgelassen</button></div></div>`).join('')}<p class="muted">Deine Definitionen und Favoriten änderst du unter „Mein Kompass“.</p>`;
    body.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const o=opts.find(x=>x.id===b.dataset.choice),f=C.feedback(o,profile);body.querySelectorAll('[data-choice]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const box=body.querySelector('#response');box.innerHTML=`<div class="card"><p class="quote"><b>Madlene:</b> ${esc(f.madeleine)}</p><p class="quote"><b>John:</b> ${esc(f.john)}</p><label>Dein konkreter nächster Schritt<input maxlength="400" value="${esc(f.next)}"></label><button data-write ${online?'':'disabled'}>Für heute vornehmen</button><small> Erst deine Bestätigung macht daraus ein Vorhaben.</small></div>`;box.querySelector('button').onclick=async()=>{if(await mutate({op:'plan',id:o.id,label:o.label,next:box.querySelector('input').value,eventId:crypto.randomUUID()}))render();};});
    for(const [attr,state] of [['done','erledigt'],['skip','ausgelassen']])body.querySelectorAll('[data-'+attr+']').forEach(b=>b.onclick=async()=>{const id=b.dataset[attr],sel=[...body.querySelectorAll('[data-effect]')].find(x=>x.dataset.effect===id);if(await mutate({op:'result',eventId:id,status:state,effect:state==='erledigt'?sel.value:'offen'})){render();note(state==='erledigt'?'Gut gemacht: Du hast dein Vorhaben umgesetzt. Deine Rückmeldung fließt in die nächsten Vorschläge ein. Morgen kannst du bewusst etwas anderes wählen – etwa Verbindung statt Aktivität oder Ruhe statt eines weiteren Programms.':'Für heute ausgelassen. Beim nächsten Mal kannst du einen kleineren Schritt oder etwas anderes wählen.');}});
  }
  function compass(){body.innerHTML=`<h3>Deine Bedeutung zählt</h3><label>Was heißt für dich ein tugendhaftes Leben?<textarea id="values" maxlength="1200">${esc(profile.values)}</textarea></label><label>Was soll ein guter Abend dir geben?<textarea id="definition" maxlength="1200">${esc(profile.definition)}</textarea></label><label>Johns Direktheit<select id="directness">${[['sanft','Sanft'],['klar','Klar'],['direkt','Sehr direkt']].map(([v,l])=>`<option value="${v}" ${profile.directness===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Madlenes spirituelle Sprache<select id="spirituality">${[['zurueckhaltend','Zurückhaltend'],['offen','Offen'],['vertieft','Vertieft']].map(([v,l])=>`<option value="${v}" ${profile.spirituality===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Johns persönliche Denkimpulse<input id="john-influence" maxlength="600" value="${esc(profile.influences.john)}"></label><label>Madlenes persönliche Denkimpulse<input id="mad-influence" maxlength="600" value="${esc(profile.influences.madeleine)}"></label><h3>Deine eigenen Möglichkeiten</h3><p class="muted">Je Zeile: Bezeichnung | deine Definition. Unveränderte Bezeichnungen behalten ihre Kennung.</p><textarea id="custom" aria-label="Eigene Abendmöglichkeiten und Definitionen" rows="4">${esc((profile.custom||[]).map(o=>o.label+' | '+o.definition).join('\n'))}</textarea><h3>Favoriten</h3>${C.catalog(profile).map(o=>`<label><input type="checkbox" data-favorite="${esc(o.id)}" ${(profile.favorites||[]).includes(o.id)?'checked':''}> ${esc(o.label)}</label>`).join('')}<button id="save-profile" data-write>Persönliches Profil speichern</button>`;
    body.querySelector('#save-profile').onclick=async()=>{const lines=body.querySelector('#custom').value.split('\n').filter(s=>s.trim());if(lines.length>20){note('Bitte höchstens 20 eigene Möglichkeiten eintragen.');return;}const custom=lines.map((line,i)=>{const [label,...def]=line.split('|');return {id:profile.custom.find(x=>x.label===label.trim())?.id||'custom-'+crypto.randomUUID(),label:label.trim(),definition:def.join('|').trim()};});const p={op:'profile',values:body.querySelector('#values').value,definition:body.querySelector('#definition').value,directness:body.querySelector('#directness').value,spirituality:body.querySelector('#spirituality').value,influences:{john:body.querySelector('#john-influence').value,madeleine:body.querySelector('#mad-influence').value},custom,favorites:[...body.querySelectorAll('[data-favorite]:checked')].map(x=>x.dataset.favorite)};if(await mutate(p))render();};
  }
  async function guides(){body.innerHTML='<p>Wegweiser werden geladen …</p>';try{if(!guideData.length){const r=await fetch(new URL('avatar-guides.json',base));if(!r.ok)throw Error();guideData=await r.json();}if(active!=='wegweiser')return;body.innerHTML='<h3>30 Wegweiser · deine eigene Haltung</h3><p>Eine Auswahl aus verschiedenen Traditionen der letzten rund 4.000 Jahre. Sie beginnt hier im ersten Jahrtausend vor unserer Zeitrechnung. Datierungen sind teils unsicher. Ein hilfreicher Gedanke bedeutet keine Zustimmung zu einer ganzen Lehre.</p>'+guideData.map(g=>{const r=profile.ratings[g.id]||{};return `<article class="guide"><h3>${esc(g.name)}</h3><small>${esc(g.period)} · ${esc(g.tradition)}</small><p>${esc(g.core)}</p><p><b>Im Alltag:</b> ${esc(g.practice)}</p><p class="muted">${esc(g.tension)}</p><a href="${esc(g.source)}" target="_blank" rel="noopener noreferrer">Quelle / Vertiefung ↗</a><label>Für dich relevant?<select data-rating="${g.id}">${[['offen','Noch offen'],['relevant','Relevant'],['teilweise','Teilweise'],['nein','Nicht relevant']].map(([v,l])=>`<option value="${v}" ${r.rating===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Welcher Gedanke passt – und welcher nicht?<textarea maxlength="500" data-note="${g.id}">${esc(r.note||'')}</textarea></label><button data-write data-rate="${g.id}" ${online?'':'disabled'}>Bewertung speichern</button></article>`;}).join('');body.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>mutate({op:'rating',id:b.dataset.rate,rating:body.querySelector('[data-rating="'+b.dataset.rate+'"]').value,note:body.querySelector('[data-note="'+b.dataset.rate+'"]').value}));}catch{body.textContent='Die Wegweiser konnten nicht geladen werden. Bitte erneut öffnen.';}}
  let conversation=[];
  function personalities(){body.innerHTML=`<h3>Ein Master, dein persönlicher Ausdruck</h3><p>Master und persönliche Anpassungen bleiben getrennt. Master-Version: <b>${esc(master?.version||'nicht verbunden')}</b>. Profil-Version: ${profile.revision}.</p>`+['john','madeleine'].map(a=>`<div class="card"><h3>${icons[a]} ${names[a]}</h3><span class="badge">Master</span><p>${esc(master?.[a]?.role||(a==='john'?'Realistischer Unternehmer und Gegenprüfer':'Spirituelle Seele, Firmen-Coach, CFO und Kritikerin'))}</p><p>${esc(master?.[a]?.voice||'Verbinde die Wolke, um die aktive Master-Persönlichkeit zu sehen.')}</p><span class="badge">Persönliches Profil</span><p>${esc(profile.influences[a]||'Noch keine eigenen Denkimpulse festgelegt.')}</p></div>`).join('')+`<p>Deine Bewertungen, Erinnerungen und Definitionen werden nicht in andere Instanzen ausgerollt.</p><button id="talk">Mit ${names[selected]} sprechen</button><p id="talk-state" role="status"></p>`;body.querySelector('#talk').onclick=()=>{
    const slot=body.querySelector('#talk-state');slot.innerHTML='<label>Deine Frage an '+names[selected]+'<textarea maxlength="4000" rows="3"></textarea></label><button data-write '+(online?'':'disabled')+'>Frage senden</button><div class="answer" aria-live="polite"></div>';
    const send=slot.querySelector('button');send.onclick=async()=>{const input=slot.querySelector('textarea'),text=input.value.trim();if(!text||busy)return;busy=true;send.disabled=true;slot.querySelector('.answer').textContent='Antwort wird vorbereitet …';try{const messages=conversation.slice(-6).concat({role:'user',content:text});const d=await request({op:'chat',avatar:selected,messages});conversation=messages.concat({role:'assistant',content:d.text});slot.querySelector('.answer').textContent=d.text;input.value='';}catch(e){slot.querySelector('.answer').textContent=e.message;}finally{busy=false;send.disabled=!online;}};
  };}
  shadow.querySelectorAll('[data-avatar]').forEach(b=>b.onclick=()=>open('persoenlichkeit',b.dataset.avatar));shadow.querySelector('.fab').onclick=()=>open();shadow.querySelector('#close').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});shadow.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.tab;render();});
  window.AvatarUI={open,profile:()=>profile,options:()=>C.ranked(profile),feedback:o=>C.feedback(o,profile),save:mutate,reload:()=>request(),ready:()=>online};
  // Loading the profile consumes no model tokens. Missing setup remains a visible state on opening.
  if(endpoint())request().catch(()=>{});
})();
